### ISSUE TITLE
Plugin NOT working with Photoshop CS6

### ISSUE THREAD

**Issue by sandroqz** [nathansmith/960-Grid-System#26]
Hi, guys!

Is 960.gs plugin compatible with Photoshop CS6?

I couldn't install it.

I copied 960_GRIDS.atn to "/Applications/Adobe Photoshop CS6/Presets/Actions" then I opened PS and there is nothing in Actions window.

After that I tried to move 960_GRIDS.atn from "/Applications/Adobe Photoshop CS6/Presets/Actions" to "/Users/sandro/Library/Application Support/Adobe/Adobe Photoshop CS6/Presets/Actions" then I closed PS and re-opened it, but with no luck too. :(

I've no idea what's going on.

Can you please help-me? Thanks in advance.

**Comment by MyaoYL** [comment]
GREAT! THX!

**Comment by naldinho70** [comment]
perfect thank you, working in Adobe Photoshop CC 2015.5
