### ISSUE TITLE
licence with GPL or MIT

### ISSUE THREAD

**Issue by LeaYeh** [nathansmith/960-Grid-System#31]
we are cdnjs team (https://github.com/cdnjs/cdnjs), we want to host/add your project `960-Grid-System` on cdnjs,
but here is a problem that we need clearly licence,
could you please help me to figure it out?

**Comment by nathansmith** [comment]
Go with the MIT license. It's more permissive.

I just have GPL in there too, since some projects (Drupal, WordPress) require GPL in order to use.

**Comment by michaelcullum** [comment]
@nathansmith A GPL project can include MIT libraries as the GPL is a stricter license.

**Comment by LeaYeh** [comment]
ok, thank you @nathansmith
