### ISSUE TITLE
Convert to 1260px version

### ISSUE THREAD

**Issue by vishy93** [nathansmith/960-Grid-System#35]
Hi Nathan,

May I as what calculation you used for the grid sizing, as I would like to make a 24 col for 1260px wide?

**Comment by nathansmith** [comment]
You may find this site helpful…

http://gridcalculator.dk/#/1260/24/20/10

**Comment by jrennemeyer** [comment]
Unfortunately, that site doesn't generate CSS. The Custom CSS Generator link on your site links to a boilerplate apache page.

**Comment by nathansmith** [comment]
@jrennemeyer Thanks for the heads-up. Unfortunately, these various third party CSS generator sites have gone on/offline over the years.

I think this one works…

https://trungdq88.github.io/960-grid-generator/
